project:
  type: website
  output-dir: _site

website:
  navbar:
    right:
      - href: /index.html
        text: "⌂"
      - href: /projects.html
        text: "Projects"
  search: false

format:
  html:
    theme: flatly
    css: /styles.css
    self-contained: false
    embedded-resources: false
    toc: false

editor: visual

execute: 
  freeze: auto
