project:
  type: website

website:
  navbar:
    right:
      - href: index.qmd
        text: Landing Page
      - about.qmd

format:
  html:
    theme: 
    - litera
    - brand
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto

