project:
  type: website

website:
  navbar:
    right:
      - href: index.qmd
        text: "⌂"
      - href: projects.qmd
        text: "Projects"
  search: false

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

editor: visual

execute: 
  freeze: auto
